Tum:derleme calistirma




derleme:
		g++ -I ./include/ -o ./lib/dugum.o -c ./src/dugum.cpp
		g++ -I ./include/ -o ./lib/yigit.o -c ./src/yigit.cpp
		g++ -I ./include/ -o ./lib/avl.o -c ./src/avl.cpp
		g++ -I ./include/ -o ./lib/avldugum.o -c ./src/avldugum.cpp
	 
		
		
		g++ -I ./include/ -o ./bin/Test ./lib/dugum.o ./lib/yigit.o ./lib/avl.o ./lib/avldugum.o ./src/Test.cpp
			
calistirma:
	./bin/Test
	
	
	Tum:derleme calistirma

 